//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentler.ExternalServices.PayForward {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://secure.modpay.com/netservices/payforward", ConfigurationName="ExternalServices.PayForward.PayforwardSoap")]
    public interface PayforwardSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://secure.modpay.com/netservices/payforward/authUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool authUser(long clientId, string wsPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://secure.modpay.com/netservices/payforward/CreatePayforwardPayee", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        long CreatePayforwardPayee(
                    long clientId, 
                    string wsPassword, 
                    string customerAccount, 
                    string firstName, 
                    string lastName, 
                    string companyName, 
                    string address, 
                    string city, 
                    string state, 
                    string zip, 
                    string country, 
                    string phone, 
                    string fax, 
                    string email, 
                    string routingAba, 
                    string bankAccountNum, 
                    string nameOnAccount, 
                    string accountType);
        
        // CODEGEN: Generating message contract since the wrapper name (CreatePayforwardPayeeWithStatus) of message CreatePayforwardPayeeWithStatus does not match the default value (CreatePayforwardPayee1)
        [System.ServiceModel.OperationContractAttribute(Action="https://secure.modpay.com/netservices/payforward/CreatePayforwardPayeeWithStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Rentler.ExternalServices.PayForward.CreatePayforwardPayeeWithStatus1 CreatePayforwardPayee1(Rentler.ExternalServices.PayForward.CreatePayforwardPayeeWithStatus request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://secure.modpay.com/netservices/payforward/CreatePayforwardPayment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        long CreatePayforwardPayment(long clientId, string wsPassword, long payeeId, System.DateTime pmtDate, double pmtAmount, int pmtType);
        
        // CODEGEN: Generating message contract since the wrapper name (CreatePayforwardPaymentWithCustomData) of message CreatePayforwardPaymentWithCustomData does not match the default value (CreatePayforwardPayment1)
        [System.ServiceModel.OperationContractAttribute(Action="https://secure.modpay.com/netservices/payforward/CreatePayforwardPaymentWithCusto" +
            "mData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Rentler.ExternalServices.PayForward.CreatePayforwardPaymentWithCustomData1 CreatePayforwardPayment1(Rentler.ExternalServices.PayForward.CreatePayforwardPaymentWithCustomData request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://secure.modpay.com/netservices/payforward/FindPayees", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet FindPayees(long clientId, string wsPassword, long customerId, string customerAccount, string firstName, string lastName, string companyName, string bankAccountNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://secure.modpay.com/netservices/payforward/isValidRoutingABA", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool isValidRoutingABA(string routingAba);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://secure.modpay.com/netservices/payforward/ModifyPayee", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        long ModifyPayee(
                    long clientId, 
                    string wsPassword, 
                    string customerAccount, 
                    long payeeId, 
                    string firstName, 
                    string lastName, 
                    string companyName, 
                    string address, 
                    string city, 
                    string state, 
                    string zip, 
                    string country, 
                    string phone, 
                    string fax, 
                    string email, 
                    string routingAba, 
                    string bankAccountNum, 
                    string nameOnAccount, 
                    string accountType);
        
        // CODEGEN: Generating message contract since the wrapper name (ModifyPayeeWithStatus) of message ModifyPayeeWithStatus does not match the default value (ModifyPayee1)
        [System.ServiceModel.OperationContractAttribute(Action="https://secure.modpay.com/netservices/payforward/ModifyPayeeWithStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Rentler.ExternalServices.PayForward.ModifyPayeeWithStatus1 ModifyPayee1(Rentler.ExternalServices.PayForward.ModifyPayeeWithStatus request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreatePayforwardPayeeWithStatus", WrapperNamespace="https://secure.modpay.com/netservices/payforward", IsWrapped=true)]
    public partial class CreatePayforwardPayeeWithStatus {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://secure.modpay.com/netservices/payforward", Order=0)]
        public long clientId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://secure.modpay.com/netservices/payforward", Order=1)]
        public string wsPassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://secure.modpay.com/netservices/payforward", Order=2)]
        public string customerAccount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://secure.modpay.com/netservices/payforward", Order=3)]
        public string firstName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://secure.modpay.com/netservices/payforward", Order=4)]
        public string lastName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://secure.modpay.com/netservices/payforward", Order=5)]
        public string companyName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://secure.modpay.com/netservices/payforward", Order=6)]
        public string address;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://secure.modpay.com/netservices/payforward", Order=7)]
        public string city;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://secure.modpay.com/netservices/payforward", Order=8)]
        public string state;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://secure.modpay.com/netservices/payforward", Order=9)]
        public string zip;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://secure.modpay.com/netservices/payforward", Order=10)]
        public string country;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://secure.modpay.com/netservices/payforward", Order=11)]
        public string phone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://secure.modpay.com/netservices/payforward", Order=12)]
        public string fax;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://secure.modpay.com/netservices/payforward", Order=13)]
        public string email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://secure.modpay.com/netservices/payforward", Order=14)]
        public string routingAba;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://secure.modpay.com/netservices/payforward", Order=15)]
        public string bankAccountNum;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://secure.modpay.com/netservices/payforward", Order=16)]
        public string nameOnAccount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://secure.modpay.com/netservices/payforward", Order=17)]
        public string accountType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://secure.modpay.com/netservices/payforward", Order=18)]
        public int activeInactiveStatus;
        
        public CreatePayforwardPayeeWithStatus() {
        }
        
        public CreatePayforwardPayeeWithStatus(
                    long clientId, 
                    string wsPassword, 
                    string customerAccount, 
                    string firstName, 
                    string lastName, 
                    string companyName, 
                    string address, 
                    string city, 
                    string state, 
                    string zip, 
                    string country, 
                    string phone, 
                    string fax, 
                    string email, 
                    string routingAba, 
                    string bankAccountNum, 
                    string nameOnAccount, 
                    string accountType, 
                    int activeInactiveStatus) {
            this.clientId = clientId;
            this.wsPassword = wsPassword;
            this.customerAccount = customerAccount;
            this.firstName = firstName;
            this.lastName = lastName;
            this.companyName = companyName;
            this.address = address;
            this.city = city;
            this.state = state;
            this.zip = zip;
            this.country = country;
            this.phone = phone;
            this.fax = fax;
            this.email = email;
            this.routingAba = routingAba;
            this.bankAccountNum = bankAccountNum;
            this.nameOnAccount = nameOnAccount;
            this.accountType = accountType;
            this.activeInactiveStatus = activeInactiveStatus;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreatePayforwardPayeeWithStatusResponse", WrapperNamespace="https://secure.modpay.com/netservices/payforward", IsWrapped=true)]
    public partial class CreatePayforwardPayeeWithStatus1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://secure.modpay.com/netservices/payforward", Order=0)]
        public long CreatePayforwardPayeeWithStatusResult;
        
        public CreatePayforwardPayeeWithStatus1() {
        }
        
        public CreatePayforwardPayeeWithStatus1(long CreatePayforwardPayeeWithStatusResult) {
            this.CreatePayforwardPayeeWithStatusResult = CreatePayforwardPayeeWithStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreatePayforwardPaymentWithCustomData", WrapperNamespace="https://secure.modpay.com/netservices/payforward", IsWrapped=true)]
    public partial class CreatePayforwardPaymentWithCustomData {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://secure.modpay.com/netservices/payforward", Order=0)]
        public long clientId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://secure.modpay.com/netservices/payforward", Order=1)]
        public string wsPassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://secure.modpay.com/netservices/payforward", Order=2)]
        public long payeeId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://secure.modpay.com/netservices/payforward", Order=3)]
        public System.DateTime pmtDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://secure.modpay.com/netservices/payforward", Order=4)]
        public double pmtAmount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://secure.modpay.com/netservices/payforward", Order=5)]
        public int pmtType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://secure.modpay.com/netservices/payforward", Order=6)]
        public string custData;
        
        public CreatePayforwardPaymentWithCustomData() {
        }
        
        public CreatePayforwardPaymentWithCustomData(long clientId, string wsPassword, long payeeId, System.DateTime pmtDate, double pmtAmount, int pmtType, string custData) {
            this.clientId = clientId;
            this.wsPassword = wsPassword;
            this.payeeId = payeeId;
            this.pmtDate = pmtDate;
            this.pmtAmount = pmtAmount;
            this.pmtType = pmtType;
            this.custData = custData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreatePayforwardPaymentWithCustomDataResponse", WrapperNamespace="https://secure.modpay.com/netservices/payforward", IsWrapped=true)]
    public partial class CreatePayforwardPaymentWithCustomData1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://secure.modpay.com/netservices/payforward", Order=0)]
        public long CreatePayforwardPaymentWithCustomDataResult;
        
        public CreatePayforwardPaymentWithCustomData1() {
        }
        
        public CreatePayforwardPaymentWithCustomData1(long CreatePayforwardPaymentWithCustomDataResult) {
            this.CreatePayforwardPaymentWithCustomDataResult = CreatePayforwardPaymentWithCustomDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ModifyPayeeWithStatus", WrapperNamespace="https://secure.modpay.com/netservices/payforward", IsWrapped=true)]
    public partial class ModifyPayeeWithStatus {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://secure.modpay.com/netservices/payforward", Order=0)]
        public long clientId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://secure.modpay.com/netservices/payforward", Order=1)]
        public string wsPassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://secure.modpay.com/netservices/payforward", Order=2)]
        public string customerAccount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://secure.modpay.com/netservices/payforward", Order=3)]
        public long payeeId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://secure.modpay.com/netservices/payforward", Order=4)]
        public string firstName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://secure.modpay.com/netservices/payforward", Order=5)]
        public string lastName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://secure.modpay.com/netservices/payforward", Order=6)]
        public string companyName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://secure.modpay.com/netservices/payforward", Order=7)]
        public string address;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://secure.modpay.com/netservices/payforward", Order=8)]
        public string city;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://secure.modpay.com/netservices/payforward", Order=9)]
        public string state;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://secure.modpay.com/netservices/payforward", Order=10)]
        public string zip;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://secure.modpay.com/netservices/payforward", Order=11)]
        public string country;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://secure.modpay.com/netservices/payforward", Order=12)]
        public string phone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://secure.modpay.com/netservices/payforward", Order=13)]
        public string fax;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://secure.modpay.com/netservices/payforward", Order=14)]
        public string email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://secure.modpay.com/netservices/payforward", Order=15)]
        public string routingAba;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://secure.modpay.com/netservices/payforward", Order=16)]
        public string bankAccountNum;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://secure.modpay.com/netservices/payforward", Order=17)]
        public string nameOnAccount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://secure.modpay.com/netservices/payforward", Order=18)]
        public string accountType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://secure.modpay.com/netservices/payforward", Order=19)]
        public int activeInactiveStatus;
        
        public ModifyPayeeWithStatus() {
        }
        
        public ModifyPayeeWithStatus(
                    long clientId, 
                    string wsPassword, 
                    string customerAccount, 
                    long payeeId, 
                    string firstName, 
                    string lastName, 
                    string companyName, 
                    string address, 
                    string city, 
                    string state, 
                    string zip, 
                    string country, 
                    string phone, 
                    string fax, 
                    string email, 
                    string routingAba, 
                    string bankAccountNum, 
                    string nameOnAccount, 
                    string accountType, 
                    int activeInactiveStatus) {
            this.clientId = clientId;
            this.wsPassword = wsPassword;
            this.customerAccount = customerAccount;
            this.payeeId = payeeId;
            this.firstName = firstName;
            this.lastName = lastName;
            this.companyName = companyName;
            this.address = address;
            this.city = city;
            this.state = state;
            this.zip = zip;
            this.country = country;
            this.phone = phone;
            this.fax = fax;
            this.email = email;
            this.routingAba = routingAba;
            this.bankAccountNum = bankAccountNum;
            this.nameOnAccount = nameOnAccount;
            this.accountType = accountType;
            this.activeInactiveStatus = activeInactiveStatus;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ModifyPayeeWithStatusResponse", WrapperNamespace="https://secure.modpay.com/netservices/payforward", IsWrapped=true)]
    public partial class ModifyPayeeWithStatus1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://secure.modpay.com/netservices/payforward", Order=0)]
        public long ModifyPayeeWithStatusResult;
        
        public ModifyPayeeWithStatus1() {
        }
        
        public ModifyPayeeWithStatus1(long ModifyPayeeWithStatusResult) {
            this.ModifyPayeeWithStatusResult = ModifyPayeeWithStatusResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PayforwardSoapChannel : Rentler.ExternalServices.PayForward.PayforwardSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PayforwardSoapClient : System.ServiceModel.ClientBase<Rentler.ExternalServices.PayForward.PayforwardSoap>, Rentler.ExternalServices.PayForward.PayforwardSoap {
        
        public PayforwardSoapClient() {
        }
        
        public PayforwardSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PayforwardSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PayforwardSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PayforwardSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool authUser(long clientId, string wsPassword) {
            return base.Channel.authUser(clientId, wsPassword);
        }
        
        public long CreatePayforwardPayee(
                    long clientId, 
                    string wsPassword, 
                    string customerAccount, 
                    string firstName, 
                    string lastName, 
                    string companyName, 
                    string address, 
                    string city, 
                    string state, 
                    string zip, 
                    string country, 
                    string phone, 
                    string fax, 
                    string email, 
                    string routingAba, 
                    string bankAccountNum, 
                    string nameOnAccount, 
                    string accountType) {
            return base.Channel.CreatePayforwardPayee(clientId, wsPassword, customerAccount, firstName, lastName, companyName, address, city, state, zip, country, phone, fax, email, routingAba, bankAccountNum, nameOnAccount, accountType);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Rentler.ExternalServices.PayForward.CreatePayforwardPayeeWithStatus1 Rentler.ExternalServices.PayForward.PayforwardSoap.CreatePayforwardPayee1(Rentler.ExternalServices.PayForward.CreatePayforwardPayeeWithStatus request) {
            return base.Channel.CreatePayforwardPayee1(request);
        }
        
        public long CreatePayforwardPayee1(
                    long clientId, 
                    string wsPassword, 
                    string customerAccount, 
                    string firstName, 
                    string lastName, 
                    string companyName, 
                    string address, 
                    string city, 
                    string state, 
                    string zip, 
                    string country, 
                    string phone, 
                    string fax, 
                    string email, 
                    string routingAba, 
                    string bankAccountNum, 
                    string nameOnAccount, 
                    string accountType, 
                    int activeInactiveStatus) {
            Rentler.ExternalServices.PayForward.CreatePayforwardPayeeWithStatus inValue = new Rentler.ExternalServices.PayForward.CreatePayforwardPayeeWithStatus();
            inValue.clientId = clientId;
            inValue.wsPassword = wsPassword;
            inValue.customerAccount = customerAccount;
            inValue.firstName = firstName;
            inValue.lastName = lastName;
            inValue.companyName = companyName;
            inValue.address = address;
            inValue.city = city;
            inValue.state = state;
            inValue.zip = zip;
            inValue.country = country;
            inValue.phone = phone;
            inValue.fax = fax;
            inValue.email = email;
            inValue.routingAba = routingAba;
            inValue.bankAccountNum = bankAccountNum;
            inValue.nameOnAccount = nameOnAccount;
            inValue.accountType = accountType;
            inValue.activeInactiveStatus = activeInactiveStatus;
            Rentler.ExternalServices.PayForward.CreatePayforwardPayeeWithStatus1 retVal = ((Rentler.ExternalServices.PayForward.PayforwardSoap)(this)).CreatePayforwardPayee1(inValue);
            return retVal.CreatePayforwardPayeeWithStatusResult;
        }
        
        public long CreatePayforwardPayment(long clientId, string wsPassword, long payeeId, System.DateTime pmtDate, double pmtAmount, int pmtType) {
            return base.Channel.CreatePayforwardPayment(clientId, wsPassword, payeeId, pmtDate, pmtAmount, pmtType);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Rentler.ExternalServices.PayForward.CreatePayforwardPaymentWithCustomData1 Rentler.ExternalServices.PayForward.PayforwardSoap.CreatePayforwardPayment1(Rentler.ExternalServices.PayForward.CreatePayforwardPaymentWithCustomData request) {
            return base.Channel.CreatePayforwardPayment1(request);
        }
        
        public long CreatePayforwardPayment1(long clientId, string wsPassword, long payeeId, System.DateTime pmtDate, double pmtAmount, int pmtType, string custData) {
            Rentler.ExternalServices.PayForward.CreatePayforwardPaymentWithCustomData inValue = new Rentler.ExternalServices.PayForward.CreatePayforwardPaymentWithCustomData();
            inValue.clientId = clientId;
            inValue.wsPassword = wsPassword;
            inValue.payeeId = payeeId;
            inValue.pmtDate = pmtDate;
            inValue.pmtAmount = pmtAmount;
            inValue.pmtType = pmtType;
            inValue.custData = custData;
            Rentler.ExternalServices.PayForward.CreatePayforwardPaymentWithCustomData1 retVal = ((Rentler.ExternalServices.PayForward.PayforwardSoap)(this)).CreatePayforwardPayment1(inValue);
            return retVal.CreatePayforwardPaymentWithCustomDataResult;
        }
        
        public System.Data.DataSet FindPayees(long clientId, string wsPassword, long customerId, string customerAccount, string firstName, string lastName, string companyName, string bankAccountNum) {
            return base.Channel.FindPayees(clientId, wsPassword, customerId, customerAccount, firstName, lastName, companyName, bankAccountNum);
        }
        
        public bool isValidRoutingABA(string routingAba) {
            return base.Channel.isValidRoutingABA(routingAba);
        }
        
        public long ModifyPayee(
                    long clientId, 
                    string wsPassword, 
                    string customerAccount, 
                    long payeeId, 
                    string firstName, 
                    string lastName, 
                    string companyName, 
                    string address, 
                    string city, 
                    string state, 
                    string zip, 
                    string country, 
                    string phone, 
                    string fax, 
                    string email, 
                    string routingAba, 
                    string bankAccountNum, 
                    string nameOnAccount, 
                    string accountType) {
            return base.Channel.ModifyPayee(clientId, wsPassword, customerAccount, payeeId, firstName, lastName, companyName, address, city, state, zip, country, phone, fax, email, routingAba, bankAccountNum, nameOnAccount, accountType);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Rentler.ExternalServices.PayForward.ModifyPayeeWithStatus1 Rentler.ExternalServices.PayForward.PayforwardSoap.ModifyPayee1(Rentler.ExternalServices.PayForward.ModifyPayeeWithStatus request) {
            return base.Channel.ModifyPayee1(request);
        }
        
        public long ModifyPayee1(
                    long clientId, 
                    string wsPassword, 
                    string customerAccount, 
                    long payeeId, 
                    string firstName, 
                    string lastName, 
                    string companyName, 
                    string address, 
                    string city, 
                    string state, 
                    string zip, 
                    string country, 
                    string phone, 
                    string fax, 
                    string email, 
                    string routingAba, 
                    string bankAccountNum, 
                    string nameOnAccount, 
                    string accountType, 
                    int activeInactiveStatus) {
            Rentler.ExternalServices.PayForward.ModifyPayeeWithStatus inValue = new Rentler.ExternalServices.PayForward.ModifyPayeeWithStatus();
            inValue.clientId = clientId;
            inValue.wsPassword = wsPassword;
            inValue.customerAccount = customerAccount;
            inValue.payeeId = payeeId;
            inValue.firstName = firstName;
            inValue.lastName = lastName;
            inValue.companyName = companyName;
            inValue.address = address;
            inValue.city = city;
            inValue.state = state;
            inValue.zip = zip;
            inValue.country = country;
            inValue.phone = phone;
            inValue.fax = fax;
            inValue.email = email;
            inValue.routingAba = routingAba;
            inValue.bankAccountNum = bankAccountNum;
            inValue.nameOnAccount = nameOnAccount;
            inValue.accountType = accountType;
            inValue.activeInactiveStatus = activeInactiveStatus;
            Rentler.ExternalServices.PayForward.ModifyPayeeWithStatus1 retVal = ((Rentler.ExternalServices.PayForward.PayforwardSoap)(this)).ModifyPayee1(inValue);
            return retVal.ModifyPayeeWithStatusResult;
        }
    }
}
